---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2

  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start: disable

  truthy:
    allowed-values: [true, false]
    check-keys: false