spec:
  initContainers:
  - name: plugin-loader
    image: ghcr.io/rossigee/fluent-bit-amqp-plugin-init:0.1.5 # {"$imagepolicy": "fluent-operator:fluent-bit-amqp-plugin-init"}
    volumeMounts:
    - name: plugins
      mountPath: /plugins
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  volumesMounts:
  - name: plugins
    mountPath: /usr/lib/fluent-bit
  volumes:
  - name: plugins
    emptyDir: {}