---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                1
        Daemon               off
        Log_Level            info
        Parsers_File         parsers.conf
        Plugins_File         /fluent-bit/plugins/plugins.conf
        HTTP_Server          On
        HTTP_Listen          0.0.0.0
        HTTP_Port            2020
        Health_Check         On

    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Tag                 kube.*
        Parser              cri
        DB                  /var/log/flb_kube.db
        Mem_Buf_Limit       50MB
        Skip_Long_Lines     On
        Refresh_Interval    10

    [INPUT]
        Name                systemd
        Tag                 host.*
        Systemd_Filter      _SYSTEMD_UNIT=docker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_

    [FILTER]
        Name                modify
        Match               *
        Add                 cluster_name ${CLUSTER_NAME}
        Add                 node_name ${NODE_NAME}

    [OUTPUT]
        Name                amqp_cloudevents
        Match               kube.*
        url                 ${RABBITMQ_URL}
        exchange            ${RABBITMQ_EXCHANGE}
        routing_key         kubernetes.${CLUSTER_NAME}.logs
        queue               kubernetes-logs-${CLUSTER_NAME}
        event_source        kubernetes.${CLUSTER_NAME}
        event_type          kubernetes.container.log
        durable             true

    [OUTPUT]
        Name                amqp_cloudevents
        Match               host.*
        url                 ${RABBITMQ_URL}
        exchange            ${RABBITMQ_EXCHANGE}
        routing_key         host.${CLUSTER_NAME}.logs
        queue               host-logs-${CLUSTER_NAME}
        event_source        host.${CLUSTER_NAME}
        event_type          host.system.log
        durable             true

    [OUTPUT]
        Name                stdout
        Match               *
        Format              json_lines

  parsers.conf: |
    [PARSER]
        Name         cri
        Format       regex
        Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name         json
        Format       json
        Time_Key     timestamp
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On

    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On

  plugins.conf: |
    [PLUGINS]
        Path /fluent-bit/plugins/out_amqp_cloudevents.so